### ISSUE TITLE
Compiled 10.3.0.17-20160617

### ISSUE THREAD

**Issue by zuoruizhi** [NemoAlex/mwlwifi-bin#2]
Can you help me compiled the new version 10.3.0.17-20160617.
Thanks.

**Comment by NemoAlex** [comment]
Unfortunately, after 20160601 the driver doesn't support 15.05.1 release anymore.
However you can compile OpenWrt 15.05 branch from source with the new driver.

**Comment by zuoruizhi** [comment]
OK  Thank you . I will try it.
